### PR TITLE
Update opensips

### PR DESCRIPTION
**Pull request by jeffreywilkie**
referenced opensips version

### CODE REVIEW

**Comment by danbogos** [comment]
Hi @jeffreywilkie 

Thanks for this! Please sign contributors so I can merge your contribution.

Ta,
DanB

**Comment by danbogos** [comment]
One more thing, please have a look here:
http://cgrates.readthedocs.io/en/latest/tut_opensips_installs.html

It specifically installs 2.2, so no need of adding any additional info in this case.

DanB

**Comment by jeffreywilkie** [comment]
Ok thanks. I was just searching through documents for key words, then reading the documents to see if they needed updating. I would assume any out of date docs would be archived?  I'm attempting to update information that has snagged me while learning.

**Comment by cgrates** [comment]
Sure, np.
Please note that also there is no need of any mongo/postgres info inside
the tutorial since they are built for Redis/MySQL. We would need to provide
another tutorial (different configurations) for other combination of
databases (the one which you use actually).

DanB

**Pull request closed without merging**
