### PR TITLE
Update OpenSIPS install key and version

### PR DESCRIPTION
**Pull request by razvancrainea**

### CODE REVIEW

**Comment by razvancrainea** [comment]
Actaully I've just realised that the OpenSIPS needs rework too before using 2.2.
I'll change the script accordingly and make a pull request.

**Comment by danbogos** [comment]
hi @razvancrainea 

Do u still need this PR to be merged or you are planning another one?

Ta,
DanB

**Comment by razvancrainea** [comment]
Hi Dan! 

Sorry, I was off the last 10 days.

Yes, the PR is still valid: it removes a couple of parameters that will no longer be used in the future versions, and updates the install info for the latest OpenSIPS 2.2.

Thanks,
Răzvan

**Comment by danbogos** [comment]
Hey @razvancrainea 

Thanks!
Please attach yourself to Contributors.md and I will merge it today.

Ta,
DanB

**Comment by danbogos** [comment]
Thanks!

DanB

**Pull request merged**
