### PR TITLE
Updated Tutorial to match tutorial loader files, current files create…

### PR DESCRIPTION
**Pull request by noahmehl**
… a 1007 account and not a 1005 account.

### CODE REVIEW

**Comment by danbogos** [comment]
Hey @noahmehl ,

Thanks for your PR. Before accepting it, please sign the contributors file.

DanB

**Comment by noahmehl** [comment]
Dan,

How do I do that?  I don't see anything on the docs or in github...?

Thanks!

~Noah

**Comment by danbogos** [comment]
There is a readme here:
https://github.com/cgrates/cgrates/blob/master/CONTRIBUTING.md

DanB

**Comment by noahmehl** [comment]
Ok, should be g2g.

Thanks!

~Noah

**Comment by danbogos** [comment]
Thanks!

DanB

**Pull request merged**
