### PR TITLE
basic Out of Box logging + logrotate config for deb based systems

### PR DESCRIPTION
**Pull request by anthonysomerset**
Based on the Google Groups chat, initial work for the rsyslogd and logrotate config for DEB based systems - needs review/feedback and wider testing

### CODE REVIEW

**Comment by anthonysomerset** [comment]
CI fail looks to be unrelated to this work

**Comment by danbogos** [comment]
hey @anthonysomerset 

Thanks for this. Can you please add the folder with lowercase and keep only the file name with caps? In this way we will be consistent with the rest of the system.

Cheers,
DanB

**Comment by anthonysomerset** [comment]
done

**Comment by danbogos** [comment]
Thanks!

**Pull request merged**
